name: TZ3

on: 
  push:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test with pytest
      run: pip install pytest
      run: python -m pytest
        
