name: TZ3

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      continue-on-error: true
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
    - name: Functions Test
      continue-on-error: true
      id: pytest
      run: |
        pytest
    - name: Stress Test
      continue-on-error: true
      id: stress
      run: python time_calc.py
    - name: Send outcomes of test to Telegram channel
      uses: appleboy/telegram-action@master
      with:
        to: "-1001509588088"
        token: "5088942515:AAGCpNSHihIuE-VbOL3b-p4-vrpWWIlsEdo"
        message: |
          Functions test outcome: ${{ steps.pytest.outcome }}
          Stress test outcome: ${{ steps.stress.outcome}}
          ${{ STEPS_CONTEXT }}

        
