name: TZ3

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Test with pytest
        run: |
          pytest
