name: TZ3

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest
    - name: Stress Test with time_calc.py
      run: python time_calc.py
    - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: "-1001509588088"
          token: "5088942515:AAGCpNSHihIuE-VbOL3b-p4-vrpWWIlsEdo"
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}} 

        
