name: TZ3

on: 
  push:
    branches: [master]

jobs:
  
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

  settingup:
    runs-on: windows-latest
    
    steps:
    - name: Installing pytest
      run: pip install pytest
      
  testing:
    runs-on: windows-latest

    steps: 
    - name: Test with pytest 
      run: python -m pytest
        
